-- LIVYA Assist database bootstrap contract
--
-- The migration directory is the single source of truth for the production
-- database. This file replaces the retired pre-workflow schema and is kept as
-- a guardrail so nobody accidentally provisions the old role model.
--
-- Fresh environments:
--   1. Use Supabase CLI database migrations in supabase/migrations.
--   2. Apply them in timestamp order with `supabase db reset` or `supabase db push`.
--   3. Do not use this file as a substitute for the migration history.
--
-- Production project: maewvwdjxdlcbwsrshlp
-- Repository: gearsganesh/livya-assist
--
-- Current roles:
--   SUPER_ADMIN
--   CENTER_MANAGER
--   COORDINATOR
--   CONCIERGE_AGENT
--   HOSPITAL_USER
--   PATIENT
--
-- The migrations own all current ops_* tables, columns, indexes, constraints,
-- RLS policies, private authorization helpers, workflow RPCs, storage rules,
-- and Auth account-management functions.
--
-- The old schema used legacy roles such as "Center admin", "Finance", and
-- "Viewer" and incomplete case statuses. Keeping it here would make a fresh
-- database diverge from production, so it has deliberately been retired.
--
-- This no-op keeps the file valid SQL for tooling that expects schema.sql.
select 1;
