import { createClient } from '@supabase/supabase-js';
import { openCaseWorkspace as launchCaseWorkspace } from './case-workspace.js';

const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL || 'https://maewvwdjxdlcbwsrshlp.supabase.co',
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable__edgISlScMx7zmDT1wGVpA_1N788YwM',
  { auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true} }
);
const STAGES=['ENQUIRY','ASSESSMENT','QUOTATION','ACCEPTED','TRAVEL PLANNED','IN TREATMENT','DISCHARGED','FOLLOW UP'];
const NAV=['Dashboard','Cases','Patients','Appointments','Concierge','Tasks','Billing','Hospitals','Referral network','Team & Centers'];
const ROLES=['Super admin','Coordinator','Finance','Center admin','Viewer'];
const S={user:null,staff:null,patient:null,page:'Dashboard',q:'',center:'All centers',setup:false,loading:false};
const D={centers:[],staff:[],patients:[],cases:[],appointments:[],concierge:[],tasks:[],billing:[],hospitals:[],referrers:[]};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'AED '+Number(n||0).toLocaleString('en-IN');
const superAdmin=()=>S.staff?.role==='Super admin';
const admin=()=>['Super admin','Center admin'].includes(S.staff?.role);
const canWrite=()=>['Super admin','Coordinator','Center admin'].includes(S.staff?.role);
const canFinance=()=>['Super admin','Finance'].includes(S.staff?.role);
const write=()=>canWrite()||canFinance();
const canDelete=()=>superAdmin();
const canEditModule=name=>{
  if(superAdmin()) return true;
  if(name==='billing') return canFinance();
  if(name==='hospitals'||name==='referral network'||name==='referrers') return admin();
  return canWrite();
};
const toast=s=>{const t=$('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const run=async f=>{try{await f()}catch(e){console.error(e);toast(e.message||'Operation failed')}};
const centers=()=>S.staff?.role==='Super admin'||S.staff?.scope==='All centers'?D.centers:D.centers.filter(c=>c.name===S.staff.scope);
const rows=a=>S.center==='All centers'?a:a.filter(x=>x.center_id===S.center);
const scopedRows=a=>S.center==='All centers'?a:a.filter(x=>{if(x.center_id)return x.center_id===S.center;const p=x.patient_id&&D.patients.find(p=>p.id===x.patient_id);if(p?.center_id)return p.center_id===S.center;const k=x.case_id&&D.cases.find(c=>c.id===x.case_id);if(k?.center_id)return k.center_id===S.center;return true});
const caseLabel=id=>{const c=D.cases.find(x=>x.id===id);return c?c.case_code+' · '+patient(c.patient_id):''};
const patient=id=>D.patients.find(x=>x.id===id)?.full_name||'Unknown patient';
const center=id=>D.centers.find(x=>x.id===id)?.name||'';
function Sel(label,id,a,v='',fn=x=>x){return '<label>'+label+'<select id="'+id+'">'+a.map(x=>'<option value="'+esc(fn(x).value||fn(x))+'" '+((fn(x).value||fn(x))===v?'selected':'')+'>'+esc(fn(x).label||fn(x).value||fn(x))+'</option>').join('')+'</select></label>'}
function F(label,id,type='text',v=''){return '<label>'+label+'<input id="'+id+'" type="'+type+'" value="'+esc(v)+'"></label>'}
function closeModal(){document.querySelector('.modal')?.remove()}
function modal(title,form,save){$('app').insertAdjacentHTML('beforeend','<div class="modal"><div class="dialog"><button class="close" onclick="closeModal()">×</button><h2>'+esc(title)+'</h2>'+form+'<div class="modal-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="run(()=>'+save+')">Save</button></div></div></div>')}
async function saveRow(table,id,data){const q=id?supabase.from(table).update({...data,updated_at:new Date().toISOString()}).eq('id',id):supabase.from(table).insert(data);const r=await q;if(r.error)throw r.error;closeModal();await load();toast('Saved')}
async function delRow(table,id){if(!confirm('Delete this record?'))return;const r=await supabase.from(table).delete().eq('id',id);if(r.error)throw r.error;await load();toast('Deleted')}
function head(title,add,extra=''){return '<div class="head"><div><h1>'+esc(title)+'</h1><p>Patient coordination & concierge operations</p></div><div>'+extra+(add&&canEditModule(title.toLowerCase())?'<button class="primary" onclick="'+add+'">＋ '+esc(add.split('(')[0])+'</button>':'')+'</div></div>'}
function filter(){return '<select onchange="S.center=this.value;render()"><option value="All centers"'+(S.center==='All centers'?' selected':'')+'>All centers</option>'+centers().map(c=>'<option value="'+c.id+'"'+(S.center===c.id?' selected':'')+'>'+esc(c.name)+'</option>').join('')+'</select>'}
function tablePage(title,add,cols,data){const x=data.filter(a=>JSON.stringify(a).toLowerCase().includes(S.q.toLowerCase()));return head(title,add)+'<div class="toolbar"><input placeholder="Search..." value="'+esc(S.q)+'" oninput="S.q=this.value;render()">'+filter()+'</div><section class="table"><table><thead><tr>'+cols.map(c=>'<th>'+c+'</th>').join('')+'</tr></thead><tbody>'+(x.map(a=>a.row).join('')||'<tr><td colspan="'+cols.length+'" class="empty">No records yet.</td></tr>')+'</tbody></table></section>'}
async function load(){S.loading=true;render();const q=[['centers',supabase.from('ops_centers').select('*').order('name')],['staff',supabase.from('ops_staff').select('id,full_name,email,role,scope,active').order('full_name')],['patients',supabase.from('ops_patients').select('*').order('created_at',{ascending:false})],['cases',supabase.from('ops_cases').select('*').order('created_at',{ascending:false})],['appointments',supabase.from('ops_appointments').select('*').order('appointment_date')],['concierge',supabase.from('ops_concierge').select('*').order('created_at',{ascending:false})],['tasks',supabase.from('ops_tasks').select('*').order('due_date')],['billing',supabase.from('ops_billing').select('*').order('created_at',{ascending:false})],['hospitals',supabase.from('ops_hospitals').select('*').order('name')],['referrers',supabase.from('ops_referrers').select('*').order('name')]];const r=await Promise.all(q.map(x=>x[1]));r.forEach((x,i)=>{if(x.error)throw x.error;D[q[i][0]]=x.data||[]});S.loading=false;render()}
function dashboard(){const c=rows(D.cases),due=D.billing.filter(x=>x.status==='Due'&&(S.center==='All centers'||D.patients.find(p=>p.id===x.patient_id)?.center_id===S.center)).reduce((a,x)=>a+ +x.commission,0),rev=D.concierge.filter(x=>S.center==='All centers'||D.patients.find(p=>p.id===x.patient_id)?.center_id===S.center).reduce((a,x)=>a+ +x.revenue,0);return head('Dashboard','newCase()',filter())+'<section class="cards"><button onclick="go(\'Cases\')"><small>ACTIVE CASES</small><b>'+c.filter(x=>x.status!=='DISCHARGED').length+'</b><span>'+c.filter(x=>x.status==='ENQUIRY').length+' enquiries</span></button><button onclick="go(\'Cases\')"><small>IN TREATMENT</small><b>'+c.filter(x=>x.status==='IN TREATMENT').length+'</b><span>'+c.length+' total cases</span></button><button onclick="go(\'Billing\')"><small>COMMISSION DUE</small><b>'+money(due)+'</b><span>Open invoices</span></button><button onclick="go(\'Concierge\')"><small>CONCIERGE & ANCILLARY REVENUE</small><b>'+money(rev)+'</b><span>'+D.concierge.length+' services</span></button></section><div class="two"><section class="panel"><h2>Pipeline</h2>'+STAGES.map(s=>'<button class="pipe" onclick="go(\'Cases\');S.q=\''+s+'\';render()"><span>'+s+'</span><i><em style="width:'+(c.length?Math.max(2,c.filter(x=>x.status===s).length/c.length*100):2)+'%"></em></i><b>'+c.filter(x=>x.status===s).length+'</b></button>').join('')+'</section><section class="panel"><h2>Upcoming appointments</h2>'+D.appointments.slice(0,6).map(a=>'<button class="row" onclick="editAppointment(\''+a.id+'\')"><b>'+esc(patient(a.patient_id))+'</b><span>'+esc(a.title)+' · '+esc(a.doctor||'')+'</span><small>'+esc(a.appointment_date)+' '+esc(a.appointment_time||'')+'</small></button>').join('')||'<div class="empty">No appointments yet.</div>'+'</section></div>'}
function patients(){const data=rows(D.patients).map(p=>({row:'<tr><td><b>'+esc(p.full_name)+'</b><small>'+esc(p.date_of_birth||'')+'</small></td><td>'+esc(p.phone||'')+'<small>'+esc(p.email||'')+'</small></td><td>'+esc(center(p.center_id))+'</td><td>'+esc(p.nationality||'')+'</td><td>'+D.cases.filter(c=>c.patient_id===p.id).length+'</td><td>'+(canWrite()?'<button onclick="editPatient(\''+p.id+'\')">Edit</button> <button onclick="newCase(\'\',\''+p.id+'\')">+ Case</button> ':'')+(superAdmin()?(p.app_user_id?(p.portal_enabled?'<button onclick="patientAccount(\''+p.id+'\')">Disable login</button>':'<button onclick="patientAccount(\''+p.id+'\')">Enable login</button>'):'<button onclick="patientAccount(\''+p.id+'\')">Create login</button>'):'')+(superAdmin()?'<button class="danger" onclick="delRow(\'ops_patients\',\''+p.id+'\')">Delete</button>':'')+'</td></tr>'}));return tablePage('Patients','newPatient()',['NAME','CONTACT','CENTER','NATIONALITY','CASES','ACTIONS'],data)}
function newPatient(id=''){const x=D.patients.find(p=>p.id===id)||{};const emailField=x.app_user_id?'<label>Email<input id="e" type="email" value="'+esc(x.email||'')+'" disabled></label>':F('Email','e','email',x.email);modal(id?'Edit patient':'New patient','<div class="formgrid">'+F('Full name','n','text',x.full_name)+F('Phone','p','text',x.phone)+emailField+F('Nationality','nat','text',x.nationality)+F('Country','cor','text',x.country_of_residence)+F('City','city','text',x.city)+F('Date of birth','dob','date',x.date_of_birth)+Sel('Gender','g',['','Male','Female','Other'],x.gender)+Sel('Preferred language','lang',['English','Arabic'],x.preferred_language)+Sel('Center','cen',centers(),x.center_id,x=>({value:x.id,label:x.name}))+'</div>'+F('Notes','notes','text',x.notes),'savePatient(\''+id+'\')')}
async function savePatient(id){const d={full_name:$('n').value.trim(),phone:$('p').value.trim(),email:$('e').value.trim(),nationality:$('nat').value.trim(),country_of_residence:$('cor').value.trim(),city:$('city').value.trim(),date_of_birth:$('dob').value||null,gender:$('g').value,preferred_language:$('lang').value,center_id:$('cen').value||null,notes:$('notes').value.trim()};if(!d.full_name)return toast('Patient name is required');await saveRow('ops_patients',id,d)}
function newCase(id='',pid=''){const x=D.cases.find(c=>c.id===id)||{};if(!D.patients.length&&!pid)return toast('Create a patient first');modal(id?'Edit case':'New case','<div class="formgrid">'+Sel('Patient','cp',D.patients,pid||x.patient_id,x=>({value:x.id,label:x.full_name+' · '+(x.phone||'')}))+Sel('Center','cc',centers(),x.center_id||centers()[0]?.id,x=>({value:x.id,label:x.name}))+F('Specialty','sp','text',x.specialty)+F('Procedure','pr','text',x.procedure)+F('Hospital','ho','text',x.hospital)+Sel('Coordinator','co',D.staff.filter(s=>s.active),x.coordinator_id,x=>({value:x.id,label:x.full_name}))+Sel('Priority','pri',['Normal','High','Critical'],x.priority||'Normal')+Sel('Source','src',['Walk in','Doctor referral','Online','Partner'],x.source)+F('Estimated value (AED)','val','number',x.estimated_value)+Sel('Status','st',STAGES,x.status||'ENQUIRY')+'</div>'+F('Notes','notes','text',x.notes),'saveCase(\''+id+'\')')}
async function saveCase(id){const old=D.cases.find(c=>c.id===id),d={case_code:old?.case_code||'LV-'+new Date().getFullYear()+'-'+String(D.cases.length+1).padStart(4,'0'),patient_id:$('cp').value,center_id:$('cc').value,specialty:$('sp').value,procedure:$('pr').value,hospital:$('ho').value,coordinator_id:$('co').value||null,priority:$('pri').value,source:$('src').value,estimated_value:+$('val').value||0,status:$('st').value,notes:$('notes').value};if(!d.patient_id)return toast('Select a patient first');await saveRow('ops_cases',id,d)}
function newAppointment(id=''){const x=D.appointments.find(a=>a.id===id)||{};modal(id?'Edit appointment':'New appointment','<div class="formgrid">'+Sel('Patient','ap',D.patients,x.patient_id,x=>({value:x.id,label:x.full_name}))+Sel('Case','ac',D.cases.filter(c=>!x.patient_id||c.patient_id===x.patient_id),x.case_id,x=>({value:x.id,label:caseLabel(x.id)}))+F('Title','at','text',x.title)+F('Doctor','ad','text',x.doctor)+F('Date','dt','date',x.appointment_date)+F('Time','tm','time',x.appointment_time)+Sel('Mode','am',['','In person','Video','Phone'],x.mode)+F('Location','al','text',x.location)+Sel('Status','as',['Scheduled','Confirmed','Completed','Cancelled'],x.status||'Scheduled')+'</div>'+F('Notes','an','text',x.notes),'saveAppointment(\''+id+'\')')
async function saveAppointment(id){const d={patient_id:$('ap').value,case_id:$('ac').value||null,title:$('at').value,doctor:$('ad').value,appointment_date:$('dt').value,appointment_time:$('tm').value||null,mode:$('am').value||null,location:$('al').value||null,status:$('as').value,notes:$('an').value.trim()};if(!d.patient_id||!d.title||!d.appointment_date)return toast('Patient, title and date are required');await saveRow('ops_appointments',id,d)}
function newTask(id=''){const x=D.tasks.find(a=>a.id===id)||{};modal(id?'Edit task':'New task','<div class="formgrid">'+F('Title','tt','text',x.title)+Sel('Patient','tp',D.patients,x.patient_id,x=>({value:x.id,label:x.full_name}))+Sel('Case','tc',D.cases.filter(c=>!x.patient_id||c.patient_id===x.patient_id),x.case_id,x=>({value:x.id,label:caseLabel(x.id)}))+Sel('Assigned to','ta',D.staff,x.assigned_to,x=>({value:x.id,label:x.full_name}))+Sel('Priority','pri',['Normal','High','Critical'],x.priority||'Normal')+F('Due date','td','date',x.due_date)+Sel('Status','ts',['Open','Completed','Cancelled'],x.status||'Open')+'</div>','saveTask(\''+id+'\')')
async function saveTask(id){const d={title:$('tt').value,patient_id:$('tp').value||null,case_id:$('tc').value||null,assigned_to:$('ta').value||null,priority:$('pri').value,due_date:$('td').value||null,status:$('ts').value};if(!d.title)return toast('Task title is required');await saveRow('ops_tasks',id,d)}
function newConcierge(id=''){const x=D.concierge.find(a=>a.id===id)||{};modal(id?'Edit service':'New service','<div class="formgrid">'+Sel('Patient','qp',D.patients,x.patient_id,x=>({value:x.id,label:x.full_name}))+Sel('Case','qc',D.cases.filter(c=>!x.patient_id||c.patient_id===x.patient_id),x.case_id,x=>({value:x.id,label:caseLabel(x.id)}))+F('Service','sv','text',x.service_type)+Sel('Status','qs',['Open','Assigned','Confirmed','Pending','Completed','Cancelled'],x.status||'Open')+F('Revenue (AED)','qr','number',x.revenue)+F('Service date','qd','date',x.service_date)+'</div>','saveConcierge(\''+id+'\')')
async function saveConcierge(id){const d={patient_id:$('qp').value,case_id:$('qc').value||null,service_type:$('sv').value,status:$('qs').value,revenue:+$('qr').value||0,service_date:$('qd').value||null};if(!d.service_type)return toast('Service is required');await saveRow('ops_concierge',id,d)}
function newBilling(id=''){const x=D.billing.find(a=>a.id===id)||{};modal(id?'Edit invoice':'New invoice','<div class="formgrid">'+F('Invoice number','bn','text',x.invoice_number||'INV-'+new Date().getFullYear()+'-'+String(D.billing.length+1).padStart(4,'0'))+Sel('Patient','bp',D.patients,x.patient_id,x=>({value:x.id,label:x.full_name}))+Sel('Case','bcse',D.cases.filter(c=>!x.patient_id||c.patient_id===x.patient_id),x.case_id,x=>({value:x.id,label:caseLabel(x.id)}))+F('Amount','ba','number',x.amount)+F('Commission','bcom','number',x.commission)+F('Invoice date','bd','date',x.invoice_date||new Date().toISOString().slice(0,10))+Sel('Status','bs',['Due','Collected','Cancelled'],x.status||'Due')+'</div>'+F('Notes','bnote','text',x.notes),'saveBilling(\''+id+'\')')
async function saveBilling(id){const d={invoice_number:$('bn').value,patient_id:$('bp').value||null,case_id:$('bcse').value||null,amount:+$('ba').value||0,commission:+$('bcom').value||0,invoice_date:$('bd').value||new Date().toISOString().slice(0,10),status:$('bs').value,notes:$('bnote').value.trim()};if(!d.invoice_number)return toast('Invoice number is required');await saveRow('ops_billing',id,d)}
function newHospital(){if(!admin())return toast('Administrator access required');modal('Add hospital',F('Name','gn')+F('City','gc')+F('Specialty','gs')+F('Contact','gt'),'saveHospital()')}
async function saveHospital(){await saveRow('ops_hospitals','',{name:$('gn').value,city:$('gc').value,specialty:$('gs').value,contact:$('gt').value})}
function newReferrer(){if(!admin())return toast('Administrator access required');modal('Add referrer',F('Name','rn')+F('Organization','ro')+F('Contact','rt'),'saveReferrer()')}
async function saveReferrer(){await saveRow('ops_referrers','',{name:$('rn').value,organization:$('ro').value,contact:$('rt').value})}
function editGeneric(type,id){const x=D[type].find(a=>a.id===id)||{};if(type==='concierge')return newConcierge(id);if(type==='tasks')return newTask(id);if(type==='billing')return newBilling(id);if(type==='hospitals')modal('Edit hospital',F('Name','gn','text',x.name)+F('City','gc','text',x.city)+F('Specialty','gs','text',x.specialty)+F('Contact','gt','text',x.contact),'saveHospitalEdit(\''+id+'\')');else modal('Edit referrer',F('Name','rn','text',x.name)+F('Organization','ro','text',x.organization)+F('Contact','rt','text',x.contact),'saveReferrerEdit(\''+id+'\')')}
async function saveHospitalEdit(id){const r=await supabase.from('ops_hospitals').update({name:$('gn').value,city:$('gc').value,specialty:$('gs').value,contact:$('gt').value}).eq('id',id);if(r.error)throw r.error;closeModal();await load();toast('Saved')}
async function saveReferrerEdit(id){const r=await supabase.from('ops_referrers').update({name:$('rn').value,organization:$('ro').value,contact:$('rt').value}).eq('id',id);if(r.error)throw r.error;closeModal();await load();toast('Saved')}
function newUser(id=''){if(!superAdmin())return toast('Super Admin access required');const x=D.staff.find(a=>a.id===id)||{};const emailField=id?'<label>Email<input id="ue" type="email" value="'+esc(x.email||'')+'" disabled></label>':F('Email','ue','email',x.email||S.user?.email);modal(id?'Edit user':'Add team member',F('Full name','un','text',x.full_name)+emailField+(id?'':F('Password','up','password',''))+Sel('Role','ur',ROLES,x.role||'Coordinator')+Sel('Scope','us',['All centers'].concat(D.centers.map(c=>c.name)),x.scope||S.staff.scope)+Sel('Status','ua',['Active','Inactive'],x.active===false?'Inactive':'Active'),'saveUser(\''+id+'\')')}
async function saveUser(id){if(!superAdmin())return toast('Super Admin access required');if(id){const r=await supabase.from('ops_staff').update({full_name:$('un').value,role:$('ur').value,scope:$('us').value,active:$('ua').value==='Active'}).eq('id',id);if(r.error)throw r.error;closeModal();await load();return}if($('up').value.length<8)return toast('Use an 8+ character password');const r=await supabase.functions.invoke('admin-create-user',{body:{full_name:$('un').value,email:$('ue').value,password:$('up').value,role:$('ur').value,scope:$('us').value}});if(r.error){const detail=r.data?.error||r.error.message||'Unable to create user';throw new Error(detail)}if(r.data?.error)throw new Error(r.data.error);closeModal();await load()}
function newCenter(id=''){if(!admin())return toast('Administrator access required');const x=D.centers.find(c=>c.id===id)||{};modal(id?'Edit center':'Add center',F('Center name','cn','text',x.name)+F('City','cy','text',x.city),'saveCenter(\''+id+'\')')}
async function saveCenter(id){if(!superAdmin())return toast('Super Admin access required');await saveRow('ops_centers',id,{name:$('cn').value,city:$('cy').value,active:true})}
async function deleteUser(id){if(!confirm('Delete this user?'))return;const r=await supabase.functions.invoke('admin-delete-user',{body:{user_id:id}});if(r.error)throw r.error;await load()}
async function moveCase(id,status){const r=await supabase.from('ops_cases').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;const e=await supabase.from('ops_case_events').insert({case_id:id,event_type:'STATUS',message:'Case moved to '+status,actor_id:S.user.id});if(e.error)console.warn('Case event could not be recorded',e.error);await load()}
async function openCaseWorkspace(id){await launchCaseWorkspace({supabase,caseId:id,S,D,esc,money,patient,write,superAdmin})}
function auth(){return '<div class="auth"><div class="authcard"><div class="brand livya-brand"><div class="livya-wordmark">LIVYA</div><section><small>Patient Coordination & Concierge</small></section></div><h1>'+(S.setup?'Create Super Admin':'Sign in')+'</h1>'+(S.setup?'<form onsubmit="event.preventDefault();run(bootstrap)">'+F('Full name','sn')+F('Email','se','email')+F('Password','spw','password')+'<button class="primary">Create Super Admin</button></form>':'<form onsubmit="login(event)">'+F('Email','email','email')+F('Password','password','password')+'<button class="primary">Sign in</button><button type="button" class="linkbtn" onclick="forgotPassword()">Forgot password?</button><p id="err"></p></form>')+'</div></div>'}
async function patientPortal(){const pid=S.patient.id;const [cr,ar,cen]=await Promise.all([supabase.from('ops_cases').select('*').eq('patient_id',pid).order('created_at',{ascending:false}),supabase.from('ops_appointments').select('*').eq('patient_id',pid).order('appointment_date'),supabase.from('ops_centers').select('name').eq('id',S.patient.center_id).maybeSingle()]);if(cr.error)throw cr.error;if(ar.error)throw ar.error;const cases=cr.data||[],appointments=ar.data||[],patientCenter=cen.data?.name||'';return '<div class="portal"><header class="portal-head"><div class="brand livya-brand"><div class="livya-wordmark">LIVYA</div><section><small>Patient Portal</small></section></div><button onclick="logout()">Sign out</button></header><main><section class="welcome"><div><small>PATIENT PORTAL</small><h1>Welcome, '+esc(S.patient.full_name)+'</h1><p>'+esc(S.patient.email||S.user?.email||'')+' · '+esc(S.patient.phone||'')+'</p></div></section><section class="cards"><div><small>ACTIVE CASES</small><b>'+cases.filter(x=>x.status!=='DISCHARGED').length+'</b><span>Your current care cases</span></div><div><small>APPOINTMENTS</small><b>'+appointments.filter(x=>x.status!=='Cancelled').length+'</b><span>Scheduled and upcoming</span></div><div><small>CASES</small><b>'+cases.length+'</b><span>Total care history</span></div></section><div class="two"><section class="panel"><h2>My cases</h2>'+(cases.map(x=>'<div class="row"><b>'+esc(x.case_code)+'</b><span>'+esc(x.specialty||'')+' · '+esc(x.procedure||'')+'</span><small>'+esc(x.status)+'</small><button onclick="openCaseWorkspace(\''+x.id+'\')">View journey</button></div>').join('')||'<div class="empty">No cases yet.</div>')+'</section><section class="panel"><h2>Appointments</h2>'+(appointments.map(x=>'<div class="row"><b>'+esc(x.title)+'</b><span>'+esc(x.doctor||'')+'</span><small>'+esc(x.appointment_date)+' '+esc(x.appointment_time||'')+' · '+esc(x.status)+'</small></div>').join('')||'<div class="empty">No appointments yet.</div>')+'</section></div><section class="panel"><h2>Profile</h2><div class="profilegrid"><div><small>NAME</small><b>'+esc(S.patient.full_name)+'</b></div><div><small>EMAIL</small><b>'+esc(S.patient.email||S.user?.email||'')+'</b></div><div><small>PHONE</small><b>'+esc(S.patient.phone||'')+'</b></div><div><small>CENTER</small><b>'+esc(patientCenter)+'</b></div></div></section></main></div>';}
async function patientAccount(id){if(!superAdmin())return toast('Super Admin access required');const p=D.patients.find(x=>x.id===id);if(!p)return;const title=p.app_user_id?(p.portal_enabled?'Manage patient login':'Enable patient login'):'Create patient login';const form=p.app_user_id?'<p>'+esc(p.full_name)+' · '+esc(p.email||'')+'</p><div class="modal-actions"><button onclick="managePatientAccount(\''+id+'\',\''+(p.portal_enabled?'disable':'enable')+'\')">'+(p.portal_enabled?'Disable login':'Enable login')+'</button><button onclick="managePatientAccount(\''+id+'\',\'reset\')">Reset password</button></div>':F('Login email','pe','email',p.email)+F('Initial password','pp','password','');modal(title,form,p.app_user_id?'closeModal()':'managePatientAccount(\''+id+'\',\'create\')');}
async function managePatientAccount(id,action){if(!superAdmin())return toast('Super Admin access required');const body={action,patient_id:id};if(action==='create'){body.email=$('pe').value.trim().toLowerCase();body.password=$('pp').value;if(body.password.length<8)return toast('Use an 8+ character password');}if(action==='reset'){const password=prompt('Enter the new password (8+ characters):','');if(!password||password.length<8)return toast('Use an 8+ character password');body.password=password;}const r=await supabase.functions.invoke('admin-patient-account',{body});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);closeModal();await load();toast(action==='create'?'Patient login created':action==='reset'?'Password reset':'Login status updated');}
function passwordRecovery(){modal('Set new password',F('New password','npw','password')+F('Confirm password','cpw','password'),'saveNewPassword()');}
async function saveNewPassword(){const password=$('npw').value,confirmPassword=$('cpw').value;if(password.length<8)return toast('Use an 8+ character password');if(password!==confirmPassword)return toast('Passwords do not match');const r=await supabase.auth.updateUser({password});if(r.error)throw r.error;closeModal();toast('Password updated');await boot();}
async function forgotPassword(){const email=$('email')?.value?.trim().toLowerCase();if(!email)return toast('Enter your email first');const r=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});if(r.error)throw r.error;toast('Password reset email sent');}
function shell(body){$('app').innerHTML='<div class="app"><aside><div class="brand livya-brand"><div class="livya-wordmark">LIVYA</div><section><small>Patient Coordination & Concierge</small></section></div><nav>'+NAV.map(n=>'<button class="'+(S.page===n?'active':'')+'" onclick="go(\''+n+'\')">'+esc(n)+'</button>').join('')+'</nav><footer><strong>'+esc(S.staff.full_name)+'</strong><small>'+esc(S.staff.role)+' · '+esc(S.staff.scope)+'</small><button onclick="logout()">Sign out</button></footer></aside><main><header><strong>LIVYA OPS</strong><span>'+new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})+' <i>'+esc(S.staff.full_name[0])+'</i></span></header>'+body+'</main></div>'}
function go(p){S.page=p;S.q='';render()}
async function appointments(){const data=scopedRows(D.appointments).filter(a=>JSON.stringify(a).toLowerCase().includes(S.q.toLowerCase())).map(a=>({row:'<tr><td>'+esc(patient(a.patient_id))+'</td><td>'+esc(a.title)+'</td><td>'+esc(a.doctor||'')+'</td><td>'+esc(a.appointment_date)+' '+esc(a.appointment_time||'')+'</td><td>'+esc(a.status)+'</td><td>'+(canWrite()?'<button onclick="editAppointment(\''+a.id+'\')">Edit</button> ':'')+(canDelete()?'<button class="danger" onclick="delRow(\'ops_appointments\',\''+a.id+'\')">Delete</button>':'')+'</td></tr>'}));return tablePage('Appointments','newAppointment()',['PATIENT','TITLE','DOCTOR','DATE / TIME','STATUS','ACTIONS'],data)}
function render(){if(S.patient){patientPortal().then(b=>{$('app').innerHTML=b}).catch(e=>{$('app').innerHTML='<div class="auth"><div class="authcard"><h2>Patient portal error</h2><p>'+esc(e.message)+'</p></div></div>'});return}if(!S.staff){$('app').innerHTML=auth();return}if(S.loading){$('app').innerHTML='<div class="auth"><div class="authcard"><h2>Loading LIVYA OPS…</h2></div></div>';return}let b=S.page==='Dashboard'?dashboard():S.page==='Patients'?patients():S.page==='Cases'?cases():S.page==='Appointments'?appointments():S.page==='Team & Centers'?team():cfg[S.page]?generic(S.page):team();shell(b)}
async function bootstrap(){const full_name=$('sn').value,email=$('se').value.trim().toLowerCase(),password=$('spw').value;if(password.length<8)return toast('Use an 8+ character password');const r=await supabase.functions.invoke('bootstrap-admin',{body:{full_name,email,password}});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);const x=await supabase.auth.signInWithPassword({email,password});if(x.error)throw x.error;await boot()}
async function login(e){e.preventDefault();const r=await supabase.auth.signInWithPassword({email:$('email').value.trim().toLowerCase(),password:$('password').value});if(r.error){$('err').textContent=r.error.message;return}await boot()}
async function logout(){await supabase.auth.signOut();S.user=null;S.staff=null;S.patient=null;render()}
async function boot(){const u=await supabase.auth.getUser();if(!u.data.user)return;const staff=await supabase.from('ops_staff').select('*').eq('id',u.data.user.id).maybeSingle();if(staff.error)throw staff.error;if(staff.data?.active){S.user=u.data.user;S.staff=staff.data;S.patient=null;S.setup=false;await load();return}const patient=await supabase.from('ops_patients').select('*').eq('app_user_id',u.data.user.id).eq('portal_enabled',true).maybeSingle();if(patient.error)throw patient.error;if(patient.data){S.user=u.data.user;S.staff=null;S.patient=patient.data;S.setup=false;render();return}await supabase.auth.signOut();S.user=null;S.staff=null;S.patient=null;throw new Error('Account is not active')}
supabase.auth.onAuthStateChange((event,s)=>{if(event==='PASSWORD_RECOVERY'){passwordRecovery();return}if(s&&!S.staff&&!S.patient)boot().catch(e=>toast(e.message))});
Object.assign(window,{go,render,run,bootstrap,login,forgotPassword,passwordRecovery,saveNewPassword,logout,openCaseWorkspace,newPatient,savePatient,newCase,saveCase,editPatient:id=>newPatient(id),editCase:id=>newCase(id),newAppointment,saveAppointment,editAppointment:id=>newAppointment(id),newTask,saveTask,editTask:id=>newTask(id),newConcierge,saveConcierge,editConcierge:id=>newConcierge(id),newBilling,saveBilling,editBilling:id=>newBilling(id),newHospital,newReferrer,editGeneric,newUser,saveUser,editUser:id=>newUser(id),deleteUser,newCenter,patientAccount,managePatientAccount,closeModal,caseMode,moveCase,delRow,saveHospital,saveReferrer,saveHospitalEdit,saveReferrerEdit,saveCenter,S});
render();
(async()=>{try{const s=await supabase.auth.getSession();if(s.data.session){await boot();return}const r=await supabase.functions.invoke('bootstrap-admin',{body:{action:'status'}});if(r.error)throw r.error;if(r.data?.error)throw new Error(r.data.error);S.setup=!!r.data?.needs_setup;render()}catch(e){console.error('LIVYA startup check failed:',e);S.setup=false;render()}})();function cases(){return head('Cases','newCase()',filter())+'<div class="toolbar"><input placeholder="Search cases..." value="'+esc(S.q)+'" oninput="S.q=this.value;render()"><button onclick="caseMode(\'board\')">Board</button><button onclick="caseMode(\'list\')">List</button></div><div id="caseview">'+caseBoard(rows(D.cases))+'</div>'}
function caseBoard(c){return '<div class="board">'+STAGES.map(s=>'<section><h3>'+s+'<b>'+c.filter(x=>x.status===s).length+'</b></h3>'+c.filter(x=>x.status===s).map(x=>'<article><small>'+esc(x.case_code)+'</small><b>'+esc(patient(x.patient_id))+'</b><span>'+esc(x.specialty||'')+' · '+esc(x.procedure||'')+'</span><span>'+esc(x.hospital||'')+'</span><label>'+esc(x.priority)+'</label><div><button onclick="openCaseWorkspace(\''+x.id+'\')">Open workspace</button>'+(write()?'<select onchange="moveCase(\''+x.id+'\',this.value)">'+STAGES.map(z=>'<option'+(z===x.status?' selected':'')+'>'+z+'</option>').join('')+'</select> <button onclick="editCase(\''+x.id+'\')">Edit</button>':'')+(superAdmin()?'<button class="danger" onclick="delRow(\'ops_cases\',\''+x.id+'\')">Delete</button>':'')+'</div></article>').join('')+'</section>').join('')+'</div>'}
function caseMode(m){const c=rows(D.cases).filter(x=>JSON.stringify(x).toLowerCase().includes(S.q.toLowerCase()));$('caseview').innerHTML=m==='list'?'<div class="table"><table><thead><tr><th>CASE</th><th>PATIENT</th><th>STATUS</th><th>VALUE</th><th>ACTIONS</th></tr></thead><tbody>'+(c.map(x=>'<tr><td>'+esc(x.case_code)+'</td><td>'+esc(patient(x.patient_id))+'</td><td>'+esc(x.status)+'</td><td>'+money(x.estimated_value)+'</td><td><button onclick="openCaseWorkspace(\''+x.id+'\')">Open workspace</button> '+(write()?'<button onclick="editCase(\''+x.id+'\')">Edit</button> ':'')+(superAdmin()?'<button class="danger" onclick="delRow(\'ops_cases\',\''+x.id+'\')">Delete</button>':'')+'</td></tr>').join('')||'<tr><td colspan="5" class="empty">No cases found.</td></tr>')+'</tbody></table></div>':caseBoard(c)}
const cfg={Concierge:['concierge','Concierge','newConcierge()',[['PATIENT','patient_id'],['CASE','case_id'],['SERVICE','service_type'],['STATUS','status'],['REVENUE','revenue']]],Tasks:['tasks','Tasks','newTask()',[['TITLE','title'],['PATIENT','patient_id'],['CASE','case_id'],['PRIORITY','priority'],['DUE','due_date'],['STATUS','status']]],Billing:['billing','Billing','newBilling()',[['INVOICE','invoice_number'],['PATIENT','patient_id'],['CASE','case_id'],['AMOUNT','amount'],['COMMISSION','commission'],['STATUS','status']]],Hospitals:['hospitals','Hospitals','newHospital()',[['NAME','name'],['CITY','city'],['SPECIALTY','specialty'],['CONTACT','contact']]],'Referral network':['referrers','Referral network','newReferrer()',[['NAME','name'],['ORGANIZATION','organization'],['CONTACT','contact']]]};
function generic(name){const c=cfg[name];const data=scopedRows(D[c[0]]).map(x=>({row:'<tr>'+c[3].map(f=>'<td>'+esc(f[1]==='patient_id'?patient(x[f[1]]):f[1]==='case_id'?caseLabel(x[f[1]]):['amount','commission','revenue'].includes(f[1])?money(x[f[1]]):x[f[1]]||'')+'</td>').join('')+'<td>'+(canEditModule(name.toLowerCase())?'<button onclick="editGeneric(\''+c[0]+'\',\''+x.id+'\')">Edit</button> ':'')+(superAdmin()?'<button class="danger" onclick="delRow(\'ops_'+c[0]+'\',\''+x.id+'\')">Delete</button>':'')+'</td></tr>'}));return tablePage(c[1],c[2],c[3].map(x=>x[0]).concat('ACTIONS'),data)}
function team(){return tablePage('Team & Centers',superAdmin()?'newUser()':null,['NAME','EMAIL','ROLE','SCOPE','STATUS','ACTIONS'],D.staff.map(x=>({row:'<tr><td>'+esc(x.full_name)+'</td><td>'+esc(x.email||'')+'</td><td>'+esc(x.role)+'</td><td>'+esc(x.scope)+'</td><td>'+(x.active?'Active':'Inactive')+'</td><td>'+(superAdmin()?'<button onclick="editUser(\''+x.id+'\')">Edit</button> <button class="danger" onclick="deleteUser(\''+x.id+'\')">Delete</button>':'')+'</td></tr>'})))+'<section class="panel lower"><h2>Centers</h2>'+(superAdmin()?'<button class="primary" onclick="newCenter()">＋ Add center</button>':'')+'<div class="centergrid">'+centers().map(c=>'<div><b>'+esc(c.name)+'</b><span>'+esc(c.city||'')+'</span>'+(superAdmin()?'<button onclick="newCenter(\''+c.id+'\')">Edit</button> <button class="danger" onclick="delRow(\'ops_centers\',\''+c.id+'\')">Delete</button>':'')+'</div>').join('')+'</div></section>'}
