const KEY='livya_ops_local_v4', SESSION='livya_ops_session_v4';
const STAGES=['ENQUIRY','ASSESSMENT','QUOTATION','ACCEPTED','TRAVEL PLANNED','IN TREATMENT','DISCHARGED','FOLLOW UP'];
const NAV=['Dashboard','Cases','Patients','Concierge','Tasks','Billing','Hospitals','Referral network','Team & Centers'];
const ROLES=['Super admin','Coordinator','Finance','Center admin','Viewer'];
const blank=()=>({users:[],patients:[],cases:[],appointments:[],concierge:[],tasks:[],billing:[],hospitals:[],referrers:[],centers:[
 {id:'c1',name:'LIVYA Dubai (Master Center)',city:'Dubai',active:true},{id:'c2',name:'LIVYA Muscat',city:'Muscat',active:true},{id:'c3',name:'LIVYA Abu Dhabi',city:'Abu Dhabi',active:true},{id:'c4',name:'LIVYA Al Ain',city:'Al Ain',active:true},{id:'c5',name:'LIVYA Manama',city:'Manama',active:true}]});
let db=(()=>{try{return {...blank(),...JSON.parse(localStorage.getItem(KEY)||'null')}}catch{return blank()}})();
let session=localStorage.getItem(SESSION), page='Dashboard', filter='All centers', q='';
const $=id=>document.getElementById(id), uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const me=()=>db.users.find(x=>x.id===session), write=()=>!!me()&&me().role!=='Viewer', admin=()=>!!me()&&['Super admin','Center admin'].includes(me().role);
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)); const money=n=>'AED '+Number(n||0).toLocaleString('en-IN');
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function go(p){page=p;q='';render()} function logout(){session=null;localStorage.removeItem(SESSION);render()}
function centerSelect(){return `<select onchange="filter=this.value;render()"><option>All centers</option>${db.centers.map(c=>`<option ${filter===c.name?'selected':''}>${esc(c.name)}</option>`).join('')}</select>`}
function scoped(a){return filter==='All centers'?a:a.filter(x=>x.center===filter)}
function patientName(id){return db.patients.find(p=>p.id===id)?.name||'Unknown patient'}
function shell(body){$('app').innerHTML=`<div class="app"><aside><div class="brand"><b>L</b><section><strong>LIVYA</strong><small>Patient Coordination & Concierge</small></section></div><nav>${NAV.map(n=>`<button class="${page===n?'active':''}" onclick="go('${n}')">${esc(n)}</button>`).join('')}</nav><footer><strong>${esc(me().name)}</strong><small>${esc(me().role)} · ${esc(me().scope||'All centers')}</small><button onclick="logout()">Sign out</button></footer></aside><main><header><strong>LIVYA OPS</strong><span>${new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})} <i>${esc(me().name[0])}</i></span></header>${body}</main></div>`}
function head(title,button,extra=''){return `<div class="head"><div><h1>${title}</h1><p>Patient coordination & concierge operations</p></div><div>${extra}${button&&write()?`<button class="primary" onclick="${button}">＋ ${button.replace(/\(.*$/,'')}</button>`:''}</div></div>`}
function dashboard(){const cs=scoped(db.cases),active=cs.filter(c=>c.status!=='DISCHARGED').length,treat=cs.filter(c=>c.status==='IN TREATMENT').length,due=db.billing.filter(x=>x.status==='Due').reduce((a,x)=>a+ +x.commission,0),rev=db.concierge.reduce((a,x)=>a+ +x.revenue,0);return head('Dashboard','newCase()',centerSelect())+`<section class="cards"><button onclick="go('Cases')"><small>ACTIVE CASES</small><b>${active}</b><span>${cs.filter(c=>c.status==='ENQUIRY').length} enquiries</span></button><button onclick="go('Cases')"><small>IN TREATMENT</small><b>${treat}</b><span>${cs.length} total cases</span></button><button onclick="go('Billing')"><small>COMMISSION DUE</small><b>${money(due)}</b><span>Open invoices</span></button><button onclick="go('Concierge')"><small>CONCIERGE REVENUE</small><b>${money(rev)}</b><span>${db.concierge.length} services</span></button></section><div class="two"><section class="panel"><h2>Pipeline</h2>${STAGES.map(s=>`<button class="pipe" onclick="go('Cases');q='${s}';render()"><span>${s}</span><i><em style="width:${cs.length?Math.max(2,cs.filter(c=>c.status===s).length/cs.length*100):2}%"></em></i><b>${cs.filter(c=>c.status===s).length}</b></button>`).join('')}</section><section class="panel"><h2>Upcoming appointments</h2>${db.appointments.slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,6).map(a=>`<button class="row" onclick="editAppointment('${a.id}')"><b>${esc(patientName(a.patientId))}</b><span>${esc(a.title)} · ${esc(a.doctor||'')}</span><small>${esc(a.date)} ${esc(a.time||'')}</small></button>`).join('')||'<div class="empty">No appointments yet.</div>'}</section></div>`}
function tablePage(title,action,cols,rows){return head(title,action)+`<div class="toolbar"><input placeholder="Search..." value="${esc(q)}" oninput="q=this.value;render()">${centerSelect()}</div><section class="table"><table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${cols.length}" class="empty">No records yet.</td></tr>`}</tbody></table></section>`}
function patients(){const a=scoped(db.patients).filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));return tablePage('Patients','newPatient()', ['NAME','CONTACT','CENTER','NATIONALITY','CASES','ACTIONS'],a.map(p=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.dob||'')}</small></td><td>${esc(p.phone)}<small>${esc(p.email)}</small></td><td>${esc(p.center)}</td><td>${esc(p.nationality)}</td><td>${db.cases.filter(c=>c.patientId===p.id).length}</td><td>${write()?`<button onclick="newCase('${p.id}')">+ Case</button> <button onclick="editPatient('${p.id}')">Edit</button> <button onclick="del('patients','${p.id}')">Delete</button>`:''}</td></tr>`).join(''))}
function cases(){const a=scoped(db.cases).filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase()));return head('Cases','newCase()',centerSelect())+`<div class="toolbar"><input placeholder="Search cases..." value="${esc(q)}" oninput="q=this.value;render()"><button onclick="caseMode('board')">Board</button><button onclick="caseMode('list')">List</button></div><div id="caseview">${caseBoard(a)}</div>`}
function caseBoard(a){return `<div class="board">${STAGES.map(s=>`<section><h3>${s}<b>${a.filter(c=>c.status===s).length}</b></h3>${a.filter(c=>c.status===s).map(c=>`<article><small>${esc(c.code)}</small><b>${esc(patientName(c.patientId))}</b><span>${esc(c.specialty||'')} · ${esc(c.procedure||'')}</span><span>${esc(c.hospital||'')}</span><label>${esc(c.priority)}</label><div>${write()?`<select onchange="moveCase('${c.id}',this.value)">${STAGES.map(z=>`<option ${z===c.status?'selected':''}>${z}</option>`).join('')}</select><button onclick="editCase('${c.id}')">Edit</button><button onclick="del('cases','${c.id}')">×</button>`:''}</div></article>`).join('')}</section></div>`}
function caseMode(m){const a=scoped(db.cases);if(m==='list'){$('caseview').innerHTML=`<div class="table"><table><thead><tr><th>CASE</th><th>PATIENT</th><th>STATUS</th><th>VALUE</th><th>ACTIONS</th></tr></thead><tbody>${a.map(c=>`<tr><td>${esc(c.code)}</td><td>${esc(patientName(c.patientId))}</td><td>${esc(c.status)}</td><td>${money(c.value)}</td><td><button onclick="editCase('${c.id}')">Edit</button></td></tr>`).join('')}</tbody></table></div>`}else $('caseview').innerHTML=caseBoard(a)}
function generic(type,title,action,fields){const arr=scoped(db[type]);return tablePage(title,action,fields.map(x=>x.toUpperCase()).concat('ACTIONS'),arr.map(x=>`<tr>${fields.map(f=>`<td>${esc(x[f]??'')}</td>`).join('')}<td>${write()?`<button onclick="editGeneric('${type}','${x.id}')">Edit</button> <button onclick="del('${type}','${x.id}')">Delete</button>`:''}</td></tr>`).join(''))}
function modal(title,form,onSave){$('app').insertAdjacentHTML('beforeend',`<div class="modal"><div class="dialog"><button class="close" onclick="closeModal()">×</button><h2>${title}</h2>${form}<div class="modal-actions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="${onSave}">Save</button></div></div></div>`)}
function F(label,id,type='text',value=''){return `<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`} function S(label,id,opts,val=''){return `<label>${label}<select id="${id}">${opts.map(o=>`<option ${o===val?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`}
function patientOptions(v){return db.patients.map(p=>`<option value="${p.id}" ${p.id===v?'selected':''}>${esc(p.name)} · ${esc(p.phone)}</option>`).join('')}
function newPatient(eid=''){const x=db.patients.find(p=>p.id===eid)||{};modal(eid?'Edit patient':'New patient',`<div class="formgrid">${F('Full name','n', 'text',x.name)}${F('Phone','p','text',x.phone)}${F('Email','e','email',x.email)}${F('Nationality','nat','text',x.nationality)}${F('Country of residence','cor','text',x.country)}${F('City','city','text',x.city)}${F('Date of birth','dob','date',x.dob)}${S('Gender','g',['','Male','Female','Other'],x.gender)}${S('Preferred language','lang',['English','Arabic'],x.lang)}${S('Center','cen',db.centers.map(c=>c.name),x.center)}</div>`,`savePatient('${eid}')`)}
function savePatient(eid){const d={id:eid||uid(),name:$('n').value.trim(),phone:$('p').value.trim(),email:$('e').value.trim(),nationality:$('nat').value.trim(),country:$('cor').value.trim(),city:$('city').value.trim(),dob:$('dob').value,gender:$('g').value,lang:$('lang').value,center:$('cen').value};if(!d.name)return toast('Patient name is required');upsert('patients',d,eid);toast('Patient saved')}
function newCase(eid='',pid=''){const x=db.cases.find(c=>c.id===eid)||{};modal(eid?'Edit case':'New case',`<div class="formgrid">${S('Patient','cp',db.patients.map(p=>p.id),x.patientId||pid)}${S('Center','cc',db.centers.map(c=>c.name),x.center)}${F('Specialty','sp','text',x.specialty)}${F('Procedure','pr','text',x.procedure)}${F('Hospital','ho','text',x.hospital)}${S('Coordinator','co',db.users.map(u=>u.id),x.coordinator)}${S('Priority','pri',['Normal','High','Critical'],x.priority)}${S('Source','src',['Walk in','Doctor referral','Online','Partner'],x.source)}${F('Estimated value (AED)','val','number',x.value)}${S('Status','st',STAGES,x.status||'ENQUIRY')}</div>${F('Notes','notes','text',x.notes)}`,`saveCase('${eid}')`)}
function saveCase(eid){const old=db.cases.find(c=>c.id===eid),d={id:eid||uid(),code:old?.code||'LV-'+new Date().getFullYear()+'-'+String(db.cases.length+1).padStart(4,'0'),patientId:$('cp').value,center:$('cc').value,specialty:$('sp').value.trim(),procedure:$('pr').value.trim(),hospital:$('ho').value.trim(),coordinator:$('co').value,priority:$('pri').value,source:$('src').value,value:+$('val').value||0,status:$('st').value,notes:$('notes').value};if(!d.patientId)return toast('Select a patient first');upsert('cases',d,eid);toast('Case saved')}
function moveCase(id,status){const c=db.cases.find(x=>x.id===id);if(c){c.status=status;save();render();toast('Case moved')}}
function newAppointment(eid=''){const x=db.appointments.find(a=>a.id===eid)||{};if(!db.patients.length)return toast('Create a patient first');modal(eid?'Edit appointment':'New appointment',`<div class="formgrid">${S('Patient','ap',db.patients.map(p=>p.id),x.patientId)}${F('Title','at','text',x.title)}${F('Doctor / provider','ad','text',x.doctor)}${F('Date','dt','date',x.date)}${F('Time','tm','time',x.time)}${S('Status','as',['Scheduled','Confirmed','Completed','Cancelled'],x.status)}</div>`,`saveAppointment('${eid}')`)}
function saveAppointment(eid){const d={id:eid||uid(),patientId:$('ap').value,title:$('at').value,doctor:$('ad').value,date:$('dt').value,time:$('tm').value,status:$('as').value};if(!d.patientId||!d.title||!d.date)return toast('Patient, title and date are required');upsert('appointments',d,eid);toast('Appointment saved')}
function newTask(eid=''){const x=db.tasks.find(a=>a.id===eid)||{};modal(eid?'Edit task':'New task',`<div class="formgrid">${F('Title','tt','text',x.title)}${S('Priority','tp',['Normal','High','Critical'],x.priority)}${F('Due date','td','date',x.due)}${S('Status','ts',['Open','Completed','Cancelled'],x.status)}</div>`,`saveTask('${eid}')`)}
function saveTask(eid){const d={id:eid||uid(),title:$('tt').value,priority:$('tp').value,due:$('td').value,status:$('ts').value};if(!d.title)return toast('Task title is required');upsert('tasks',d,eid);toast('Task saved')}
function newConcierge(eid=''){const x=db.concierge.find(a=>a.id===eid)||{};if(!db.patients.length)return toast('Create a patient first');modal(eid?'Edit service':'New service',`<div class="formgrid">${S('Patient','qp',db.patients.map(p=>p.id),x.patientId)}${F('Service','sv','text',x.service)}${S('Status','qs',['Open','Assigned','Confirmed','Pending','Completed','Cancelled'],x.status)}${F('Revenue (AED)','qr','number',x.revenue)}</div>`,`saveConcierge('${eid}')`)}
function saveConcierge(eid){const d={id:eid||uid(),patientId:$('qp').value,service:$('sv').value,status:$('qs').value,revenue:+$('qr').value||0};if(!d.service)return toast('Service is required');upsert('concierge',d,eid);toast('Service saved')}
function newBilling(eid=''){const x=db.billing.find(a=>a.id===eid)||{};modal(eid?'Edit invoice':'New invoice',`<div class="formgrid">${F('Invoice number','bn','text',x.invoice)}${S('Patient','bp',db.patients.map(p=>p.id),x.patientId)}${F('Amount','ba','number',x.amount)}${F('Commission','bc','number',x.commission)}${S('Status','bs',['Due','Collected','Cancelled'],x.status)}</div>`,`saveBilling('${eid}')`)}
function saveBilling(eid){const d={id:eid||uid(),invoice:$('bn').value,patientId:$('bp').value,amount:+$('ba').value||0,commission:+$('bc').value||0,status:$('bs').value};if(!d.invoice)return toast('Invoice number is required');upsert('billing',d,eid);toast('Invoice saved')}
function editAppointment(id){newAppointment(id)} function editPatient(id){newPatient(id)} function editCase(id){newCase(id)} function editTask(id){newTask(id)} function editConcierge(id){newConcierge(id)} function editBilling(id){newBilling(id)}
function editGeneric(type,id){const x=db[type].find(a=>a.id===id)||{};const map={hospitals:[['Name','gn'],['City','gc'],['Specialty','gs'],['Contact','gt']],referrers:[['Name','rn'],['Organization','ro'],['Contact','rt']],centers:[['Name','cn'],['City','cy']]};modal('Edit '+type,map[type].map(a=>F(a[0],a[1],'text',x[type==='centers'?'name':a[0].toLowerCase()]||'')).join(''),`saveGeneric('${type}','${id}')`)}
function saveGeneric(type,id){const x=db[type].find(a=>a.id===id);if(type==='hospitals'){x.name=$('gn').value;x.city=$('gc').value;x.specialty=$('gs').value;x.contact=$('gt').value}else if(type==='referrers'){x.name=$('rn').value;x.organization=$('ro').value;x.contact=$('rt').value}else{x.name=$('cn').value;x.city=$('cy').value}save();closeModal();render();toast('Saved')}
function upsert(type,d,eid){const i=db[type].findIndex(x=>x.id===eid);if(i>=0)db[type][i]=d;else db[type].unshift(d);save();closeModal();render()}
function del(type,id){if(!confirm('Delete this record?'))return;db[type]=db[type].filter(x=>x.id!==id);save();render();toast('Deleted')}
function closeModal(){$('.modal')?.remove()}
function team(){return tablePage('Team & Centers','newUser()',['NAME','ROLE','SCOPE','STATUS','ACTIONS'],db.users.map(u=>`<tr><td>${esc(u.name)}<small>${esc(u.email)}</small></td><td>${esc(u.role)}</td><td>${esc(u.scope)}</td><td>${u.active?'Active':'Inactive'}</td><td>${admin()?`<button onclick="editUser('${u.id}')">Edit</button> <button onclick="del('users','${u.id}')">Delete</button>`:''}</td></tr>`).join('')||undefined)+`<section class="panel lower"><h2>Centers</h2><button class="primary" onclick="newCenter()">＋ Add center</button><div class="centergrid">${db.centers.map(c=>`<div><b>${esc(c.name)}</b><span>${esc(c.city)}</span>${admin()?`<button onclick="newCenter('${c.id}')">Edit</button>`:''}</div>`).join('')}</div></section>`}
function newUser(eid=''){if(!admin())return toast('Administrator access required');const x=db.users.find(u=>u.id===eid)||{};modal(eid?'Edit user':'Add team member',`<div class="formgrid">${F('Full name','un','text',x.name)}${F('Email','ue','email',x.email)}${F('Password','up','password','')}${S('Role','ur',ROLES,x.role||'Coordinator')}${F('Scope','us','text',x.scope||'All centers')}${S('Status','ua',['Active','Inactive'],x.active===false?'Inactive':'Active')}</div>`,`saveUser('${eid}')`)}
function saveUser(eid){const x=db.users.find(u=>u.id===eid),pw=$('up').value,d={id:eid||uid(),name:$('un').value,email:$('ue').value.toLowerCase(),password:pw||x?.password,role:$('ur').value,scope:$('us').value||'All centers',active:$('ua').value==='Active'};if(!d.name||!d.email||!d.password)return toast('Name, email and password are required');if(db.users.some(u=>u.email===d.email&&u.id!==eid))return toast('Email already exists');upsert('users',d,eid)}
function newCenter(eid=''){if(!admin())return toast('Administrator access required');const x=db.centers.find(c=>c.id===eid)||{};modal(eid?'Edit center':'Add center',F('Center name','cn','text',x.name)+F('City','cy','text',x.city),`saveCenter('${eid}')`)}
function saveCenter(eid){const d={id:eid||uid(),name:$('cn').value,city:$('cy').value,active:true};if(!d.name)return toast('Center name is required');upsert('centers',d,eid)}
function auth(){if(db.users.length)return `<div class="auth"><div class="authcard"><div class="brand"><b>L</b><section><strong>LIVYA</strong><small>Patient Coordination & Concierge</small></section></div><h1>Sign in</h1><form onsubmit="login(event)">${F('Email','email','email')} ${F('Password','password','password')}<button class="primary">Sign in</button><p id="err"></p></form><small>Local test mode. Supabase will replace browser credentials in production.</small></div></div>`;return `<div class="auth"><div class="authcard"><div class="brand"><b>L</b><section><strong>LIVYA</strong><small>Patient Coordination & Concierge</small></section></div><h1>Create Super Admin</h1><form onsubmit="setup(event)">${F('Full name','sn')} ${F('Email','se','email')} ${F('Password','spw','password')}<button class="primary">Create admin</button></form></div></div>`}
function setup(e){e.preventDefault();const u={id:uid(),name:$('sn').value,email:$('se').value.toLowerCase(),password:$('spw').value,role:'Super admin',scope:'All centers',active:true};if(!u.name||!u.email||u.password.length<8)return toast('Use a name, email and 8+ character password');db.users=[u];save();session=u.id;localStorage.setItem(SESSION,session);render()}
function login(e){e.preventDefault();const u=db.users.find(x=>x.email===$('email').value.toLowerCase()&&x.password===$('password').value&&x.active);if(!u){$('err').textContent='Invalid credentials or inactive account';return}session=u.id;localStorage.setItem(SESSION,session);render()}
function render(){if(!session||!me()){$('app').innerHTML=auth();return}let body='';if(page==='Dashboard')body=dashboard();else if(page==='Patients')body=patients();else if(page==='Cases')body=cases();else if(page==='Concierge')body=generic('concierge','Concierge','newConcierge()',['patientId','service','status','revenue']);else if(page==='Tasks')body=generic('tasks','Tasks','newTask()',['title','priority','due','status']);else if(page==='Billing')body=generic('billing','Billing','newBilling()',['invoice','amount','commission','status']);else if(page==='Hospitals')body=generic('hospitals','Hospitals','newHospital()',['name','city','specialty','contact']);else if(page==='Referral network')body=generic('referrers','Referral network','newReferrer()',['name','organization','contact']);else body=team();shell(body)}
window.go=go;window.logout=logout;window.login=login;window.setup=setup;window.newPatient=newPatient;window.editPatient=editPatient;window.newCase=newCase;window.editCase=editCase;window.moveCase=moveCase;window.newAppointment=newAppointment;window.editAppointment=editAppointment;window.newTask=newTask;window.editTask=editTask;window.newConcierge=newConcierge;window.editConcierge=editConcierge;window.newBilling=newBilling;window.editBilling=editBilling;window.newUser=newUser;window.editUser=editUser;window.newCenter=newCenter;window.editGeneric=editGeneric;window.saveGeneric=saveGeneric;window.saveCenter=saveCenter;window.del=del;window.closeModal=closeModal;window.caseMode=caseMode;
window.newHospital=()=>{modal('Add hospital',F('Name','gn')+F('City','gc')+F('Specialty','gs')+F('Contact','gt'),`addSimple('hospitals',{name:$('gn').value,city:$('gc').value,specialty:$('gs').value,contact:$('gt').value})`)};
window.newReferrer=()=>{modal('Add referrer',F('Name','rn')+F('Organization','ro')+F('Contact','rt'),`addSimple('referrers',{name:$('rn').value,organization:$('ro').value,contact:$('rt').value})`)};
window.addSimple=(type,d)=>{d.id=uid();db[type].unshift(d);save();closeModal();render();toast('Saved')};
render();
